Repository sonia-auv/sonia_common, pull requests merged in 2021-07, with the labels that each got.

#45 Feature/dvl message modif
  msg/BodyVelocityDVL.msg
  package.xml
Labels: Priority: High, Type: Feature

#49 Feature/fix ci workflows
  .github/workflows/docker-image-develop.yml
  .github/workflows/docker-image-feature.yml
Labels: Priority: Critical, Type: Bug

#53 Fix master workflow
  .github/workflows/docker-image-master.yml
  package.xml
Labels: Priority: High

#55 Feature/sync with master
  .vscode/settings.json
  Dockerfile
Labels: Priority: High

#54 Develop
  .github/workflows/docker-image-master.yml
  package.xml
Labels: Priority: High

#57 Feature/provider power backplane
  .vscode/launch.json
  .vscode/tasks.json
  msg/PowerMsg.msg
  package.xml
Labels: Priority: High, Type: Bug, Type: Feature

#58 Develop
  .vscode/launch.json
  .vscode/tasks.json
  msg/PowerMsg.msg
  package.xml
Labels: Priority: High, Type: Bug, Type: Feature

#59 change power msg name
  msg/PowerMsg.msg
  package.xml
Labels: Priority: High, Type: Feature

#60 change definition for kill and backplane IO to do
  msg/SendRS485Msg.msg
Labels: Priority: High, Type: Feature
