Repository sonia-auv/sonia_common, pull requests merged in 2022-04, with the labels that each got.

#98 change srv to msg to simplify code
  msg/HydroSettings.msg
  package.xml
  srv/SetHydroMode.srv
  srv/SetHydroSettings.srv
Labels: Priority: Medium, Type: Feature

#99 managed case when ROS_WS_SETUP is not set (in local use)
  package.xml
  src/sonia_common/config.h
Labels: Priority: Medium, Type: Enhancement

#101 add x,y,z values to add for debug and filtering
  msg/PingMsg.msg
  package.xml
Labels: Priority: Critical, Type: Feature

#102 Feature/pose service
  .github/pull_request_template.md
  .github/workflows/docker-image-develop.yml
  .github/workflows/docker-image-feature.yml
  .github/workflows/docker-image-fix.yml
  .github/workflows/docker-image-master.yml
  Dockerfile.cuda
  srv/ObjectPoseService.srv
  srv/SetFilterchainFilterObserver.srv
Labels: Priority: High, Type: Enhancement
