Repository sonia-auv/sonia_common, pull requests merged in 2022-02, with the labels that each got.

#87 Feature/old_msgs
  msg/ActivateAllPS.msg
  msg/AttitudeDVL.msg
  msg/CameraFeatures.msg
  msg/ControllerStates.msg
  msg/IntersubCom.msg
  msg/KillSwitchMsg.msg
  msg/MissionNameMsg.msg
  msg/MissionSwitchMsg.msg
  msg/PingerLocation.msg
  msg/PoseSavedRequest.msg
  msg/PositionTarget.msg
  msg/PowerInfo.msg
  msg/PowerMsg.msg
  package.xml
  srv/ClearWaypoint.srv
  srv/EnableControl.srv
  srv/EnableThrusters.srv
  srv/ListMissions.srv
  srv/ManagePowerSupplyBus.srv
  srv/PingerLocationService.srv
  srv/SetControlMode.srv
  srv/SetDecoupledTarget.srv
  srv/SetDepthOffset.srv
  srv/SetPositionTarget.srv
  srv/SetWorldXYOffset.srv
Labels: Priority: High, Type: Feature

#88 Update package.xml
  package.xml
Labels: Priority: High, Type: Bug

#91 Fix/serial device
  Dockerfile
  package.xml
Labels: Priority: Critical, Type: Bug
