Repository sonia-auv/sonia_common, pull requests merged in 2022-05, with the labels that each got.

#104 reverted dockerfile
  Dockerfile.cuda
Labels: Priority: Critical, Type: Bug

#105 Feature/imu cleanup srv
  package.xml
  srv/ImuDisturbance.srv
  srv/ImuResetSettings.srv
  srv/ImuTare.srv
Labels: Priority: Medium, Type: Feature

#106 Fix/workflow
  .github/workflows/docker-image-master.yml
  package.xml
Labels: Priority: Low, Type: Enhancement

#107 add message for proc-fault and underwater com
  msg/FaultDetection.msg
  msg/ModemUpdateMissionList.msg
  package.xml
  srv/ModemGetMissionList.srv
  srv/ModemUpdateMissionList.srv
Labels: Priority: Medium, Type: Feature
