Repository sonia-auv/sonia_common, pull requests merged in 2022-07, with the labels that each got.

#110 Feature/set auv unity
  srv/SetAUVService.srv
Labels: Priority: Medium, Type: Enhancement

#111 Feature/set auv unity
  package.xml
  srv/SetSimulationAUV.srv
Labels: Priority: Medium, Type: Enhancement

#113 Feature/modif hydro msg
  msg/PingMsg.msg
  package.xml
Labels: Priority: High, Type: Feature

#114 this time the service is good
  package.xml
  srv/SetSimulationAUVService.srv
Labels: Priority: Medium, Type: Bug

#115 add msg for proc nav
  msg/PingAngles.msg
  package.xml
Labels: Priority: High, Type: Feature

#117 Feature/missing info hydro
  msg/PingAngles.msg
  package.xml
Labels: Priority: High, Type: Feature

#118 added MissionTimer msg type
  msg/MissionTimer.msg
  package.xml
Labels: Priority: Low, Type: Feature

#120 Feature/edited fault warning
  msg/FaultWarning.msg
  package.xml
Labels: Priority: Low, Type: Enhancement

#121 Fixed catkin_make warns
  msg/ActuatorSendReply.msg
  msg/SendRS485Msg.msg
  package.xml
  src/sonia_common/maths/numbers.h
  src/sonia_common/maths/numbers_inl.h
  src/sonia_common/pattern/runnable.h
  src/sonia_common/pattern/runnable_inl.h
Labels: Priority: Low, Type: Bug
